name: Robô de Clima WhatsApp

on:
  schedule:
    # Roda todos os dias às 07:00 UTC (04:00 no horário de Brasília)
    - cron: '0 7 * * *'
    # Roda todos os dias às 17:00 UTC (14:00 no horário de Brasília)
    - cron: '0 17 * * *'
  # Permite que você rode manualmente pelo GitHub, se precisar
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Passo 1: Baixa o código do seu repositório
    - name: Baixar código
      uses: actions/checkout@v3

    # Passo 2: Instala o Python
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Passo 3: Instala as bibliotecas necessárias
    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas matplotlib pywhatkit

    # Passo 4: Executa o script Python
    - name: Executar o Robô de Clima
      env:
        # Pega as chaves secretas do GitHub (vamos configurar no próximo passo)
        API_KEY: ${{ secrets.WEATHER_API_KEY }}
        LOCALIZACAO: ${{ secrets.LOCATION }}
        NUMERO_WHATSAPP: ${{ secrets.PHONE_NUMBER }}
      run: python clima_bot_v2.py